### ISSUE TITLE
1.2.2 videos won't play

### ISSUE THREAD

**Issue by dnd** [skipmodea1/plugin.video.roosterteeth#1]
I have been using the rooster teeth addon for a while and it has worked great. A few days ago, however, all videos stopped playing. When you click to view it tries to open and then presents a dialog titled "Recently Added Episodes" and it says "No video found."

Did Rooster Teeth change something with their site? Maybe a different URL? Also, the videos listed for the Achievement Hunter series "How To" does not have the current show listings.

**Comment by skipmodea1** [comment]
It seems like the site changed. A new version should fix that (1.2.4).

The current episodes are all listed in "Recently Added Episodes".

**Comment by dnd** [comment]
I tried checking for updates, but the latest available mine is showing is 1.2.2. Do I need a different repository?

**Comment by skipmodea1** [comment]
It's not available in Kodi yet, it usually takes a day or two.

However u can install the zip from here, if you are in hurry: https://github.com/skipmodea1/plugin.video.roosterteeth
