### ISSUE TITLE
No videos are displayed to watch

### ISSUE THREAD

**Issue by 2haloes** [skipmodea1/plugin.video.roosterteeth#3]
After the recent website update, this plugin cannot find videos at all, noticed yesterday after the major website update, I don't know what has changed to cause this problem

EDIT: Issue appears to have fixed itself, possibly an issue on the website side

**Comment by GonadiusPrime** [comment]
Each of the children now have their own "recently added episodes".  So, the current main "recently added episodes" is showing just the roosterteeth.com recently added episodes.
The "fix" would be to add more "recently added" to the main, or add them to each child.  Your call on how you'd like to handle this.

**Comment by 2haloes** [comment]
I have to admit that I didn't notice that (When I checked the plugin a couple of days ago, it wasn't showing any RT videos at all) and I'd say to add a recently added to each child (unless someone massively against it). If I actually knew python, I'd make a fork and fix it myself
