### ISSUE TITLE
1.3.3 Error when opening episode folders 

### ISSUE THREAD

**Issue by MRamon550** [skipmodea1/plugin.video.roosterteeth#4]
Hello,

I am using version 1.3.3 of the plugin and just recently have had some issues with the plugin.  When I try and enter a folder such as "recently added episodes" or any other, I get a "Rooster teeth error - please check the log file for more information".

Checking the log, it looks like it is having an error retrieving the episode list.
11:46:36  57.333805 T:1421865888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.EOFError'>
                                            Error Contents: EOF read where object expected
                                            Traceback (most recent call last):

I have never had an error before and this just recently started.  The only thing that has changed in my configuration is I bought a new router months ago, but I have used the RT app in kodi since then.  I have also deleted the app and reinstalled it, to no avail.

Although I am a sponsor, removing the sponsor by resetting back to defaults still throws the error.  It doesn't matter if I try and access the non-sponsor content either as any opening of a folder throws the above error.

Please advise?

[kodi.log](https://github.com/skipmodea1/plugin.video.roosterteeth/files/1545863/kodi.log)

**Comment by skipmodea1** [comment]
Is this still an issue?

**Comment by MRamon550** [comment]
Hey Thanks for the response - I will check tonight.


Just saw its been updated but haven't tried since the version I posted
about.

Thanks!

**Comment by MRamon550** [comment]
Looks like the update fixed it - Thanks!
